name: Deploy static site to Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # allows manual "Run workflow" from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # publish everything from repo root

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
